# Generated by Django 3.0.6 on 2020-06-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=40)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=40)),
                ('zip', models.CharField(default='', max_length=7)),
                ('product_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=20)),
                ('product_desc', models.CharField(default='', max_length=20)),
                ('product_date', models.DateField()),
                ('product_image', models.ImageField(upload_to='shop1')),
            ],
        ),
    ]
