# Generated by Django 3.0.6 on 2020-07-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200708_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='post',
            field=models.CharField(default='', max_length=200),
        ),
    ]
