# Generated by Django 3.0.6 on 2020-07-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200711_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='post',
            field=models.CharField(default='', max_length=200),
        ),
    ]
